# Generated by Django 2.0 on 2017-12-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='childs/')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='ФИО')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('is_studying', models.BooleanField(default=True, verbose_name='Обучается')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Дети',
                'verbose_name': 'Ребёнок',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(verbose_name='Привели/Забрали')),
                ('parent', models.TextField(verbose_name='Родитель')),
                ('event_type', models.SmallIntegerField(choices=[('came', 'Пришёл'), ('away', 'Ушёл')], default='came', verbose_name='Тип')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childs.Child', verbose_name='Ребёнок')),
            ],
            options={
                'verbose_name_plural': 'Записи',
                'verbose_name': 'Запись',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childs.Group', verbose_name='Группа'),
        ),
    ]
