# Generated by Django 2.0 on 2017-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0002_auto_20171217_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('came', 'Пришёл'), ('away', 'Ушёл')], default='came', max_length=4, verbose_name='Тип'),
        ),
    ]
